# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vzhabin/server/bc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vzhabin/server/bc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vzhabin/server/bc/CMakeFiles /home/vzhabin/server/bc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vzhabin/server/bc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named g3dlite

# Build rule for target.
g3dlite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 g3dlite
.PHONY : g3dlite

# fast build rule for target.
g3dlite/fast:
	$(MAKE) -f dep/src/g3dlite/CMakeFiles/g3dlite.dir/build.make dep/src/g3dlite/CMakeFiles/g3dlite.dir/build
.PHONY : g3dlite/fast

#=============================================================================
# Target rules for targets named gsoap

# Build rule for target.
gsoap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gsoap
.PHONY : gsoap

# fast build rule for target.
gsoap/fast:
	$(MAKE) -f dep/src/gsoap/CMakeFiles/gsoap.dir/build.make dep/src/gsoap/CMakeFiles/gsoap.dir/build
.PHONY : gsoap/fast

#=============================================================================
# Target rules for targets named oregonsockets

# Build rule for target.
oregonsockets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oregonsockets
.PHONY : oregonsockets

# fast build rule for target.
oregonsockets/fast:
	$(MAKE) -f dep/src/sockets/CMakeFiles/oregonsockets.dir/build.make dep/src/sockets/CMakeFiles/oregonsockets.dir/build
.PHONY : oregonsockets/fast

#=============================================================================
# Target rules for targets named mpq

# Build rule for target.
mpq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpq
.PHONY : mpq

# fast build rule for target.
mpq/fast:
	$(MAKE) -f dep/libmpq/CMakeFiles/mpq.dir/build.make dep/libmpq/CMakeFiles/mpq.dir/build
.PHONY : mpq/fast

#=============================================================================
# Target rules for targets named revision.h

# Build rule for target.
revision.h: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 revision.h
.PHONY : revision.h

# fast build rule for target.
revision.h/fast:
	$(MAKE) -f src/genrev/CMakeFiles/revision.h.dir/build.make src/genrev/CMakeFiles/revision.h.dir/build
.PHONY : revision.h/fast

#=============================================================================
# Target rules for targets named oregonframework

# Build rule for target.
oregonframework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oregonframework
.PHONY : oregonframework

# fast build rule for target.
oregonframework/fast:
	$(MAKE) -f src/framework/CMakeFiles/oregonframework.dir/build.make src/framework/CMakeFiles/oregonframework.dir/build
.PHONY : oregonframework/fast

#=============================================================================
# Target rules for targets named shared

# Build rule for target.
shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared
.PHONY : shared

# fast build rule for target.
shared/fast:
	$(MAKE) -f src/shared/CMakeFiles/shared.dir/build.make src/shared/CMakeFiles/shared.dir/build
.PHONY : shared/fast

#=============================================================================
# Target rules for targets named oregon-realm

# Build rule for target.
oregon-realm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oregon-realm
.PHONY : oregon-realm

# fast build rule for target.
oregon-realm/fast:
	$(MAKE) -f src/oregonrealm/CMakeFiles/oregon-realm.dir/build.make src/oregonrealm/CMakeFiles/oregon-realm.dir/build
.PHONY : oregon-realm/fast

#=============================================================================
# Target rules for targets named collision

# Build rule for target.
collision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 collision
.PHONY : collision

# fast build rule for target.
collision/fast:
	$(MAKE) -f src/collision/CMakeFiles/collision.dir/build.make src/collision/CMakeFiles/collision.dir/build
.PHONY : collision/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f src/game/CMakeFiles/game.dir/build.make src/game/CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named game_pch_dephelp

# Build rule for target.
game_pch_dephelp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game_pch_dephelp
.PHONY : game_pch_dephelp

# fast build rule for target.
game_pch_dephelp/fast:
	$(MAKE) -f src/game/CMakeFiles/game_pch_dephelp.dir/build.make src/game/CMakeFiles/game_pch_dephelp.dir/build
.PHONY : game_pch_dephelp/fast

#=============================================================================
# Target rules for targets named pch_Generate_game

# Build rule for target.
pch_Generate_game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pch_Generate_game
.PHONY : pch_Generate_game

# fast build rule for target.
pch_Generate_game/fast:
	$(MAKE) -f src/game/CMakeFiles/pch_Generate_game.dir/build.make src/game/CMakeFiles/pch_Generate_game.dir/build
.PHONY : pch_Generate_game/fast

#=============================================================================
# Target rules for targets named pch_Generate_scripts

# Build rule for target.
pch_Generate_scripts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pch_Generate_scripts
.PHONY : pch_Generate_scripts

# fast build rule for target.
pch_Generate_scripts/fast:
	$(MAKE) -f src/scripts/CMakeFiles/pch_Generate_scripts.dir/build.make src/scripts/CMakeFiles/pch_Generate_scripts.dir/build
.PHONY : pch_Generate_scripts/fast

#=============================================================================
# Target rules for targets named scripts

# Build rule for target.
scripts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scripts
.PHONY : scripts

# fast build rule for target.
scripts/fast:
	$(MAKE) -f src/scripts/CMakeFiles/scripts.dir/build.make src/scripts/CMakeFiles/scripts.dir/build
.PHONY : scripts/fast

#=============================================================================
# Target rules for targets named scripts_pch_dephelp

# Build rule for target.
scripts_pch_dephelp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scripts_pch_dephelp
.PHONY : scripts_pch_dephelp

# fast build rule for target.
scripts_pch_dephelp/fast:
	$(MAKE) -f src/scripts/CMakeFiles/scripts_pch_dephelp.dir/build.make src/scripts/CMakeFiles/scripts_pch_dephelp.dir/build
.PHONY : scripts_pch_dephelp/fast

#=============================================================================
# Target rules for targets named oregon-core

# Build rule for target.
oregon-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oregon-core
.PHONY : oregon-core

# fast build rule for target.
oregon-core/fast:
	$(MAKE) -f src/oregoncore/CMakeFiles/oregon-core.dir/build.make src/oregoncore/CMakeFiles/oregon-core.dir/build
.PHONY : oregon-core/fast

#=============================================================================
# Target rules for targets named map_extractor

# Build rule for target.
map_extractor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 map_extractor
.PHONY : map_extractor

# fast build rule for target.
map_extractor/fast:
	$(MAKE) -f src/tools/map_extractor/CMakeFiles/map_extractor.dir/build.make src/tools/map_extractor/CMakeFiles/map_extractor.dir/build
.PHONY : map_extractor/fast

#=============================================================================
# Target rules for targets named vmap_assembler

# Build rule for target.
vmap_assembler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vmap_assembler
.PHONY : vmap_assembler

# fast build rule for target.
vmap_assembler/fast:
	$(MAKE) -f src/tools/vmap_assembler/CMakeFiles/vmap_assembler.dir/build.make src/tools/vmap_assembler/CMakeFiles/vmap_assembler.dir/build
.PHONY : vmap_assembler/fast

#=============================================================================
# Target rules for targets named vmap_extractor

# Build rule for target.
vmap_extractor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vmap_extractor
.PHONY : vmap_extractor

# fast build rule for target.
vmap_extractor/fast:
	$(MAKE) -f src/tools/vmap_extractor/CMakeFiles/vmap_extractor.dir/build.make src/tools/vmap_extractor/CMakeFiles/vmap_extractor.dir/build
.PHONY : vmap_extractor/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... g3dlite"
	@echo "... gsoap"
	@echo "... oregonsockets"
	@echo "... mpq"
	@echo "... revision.h"
	@echo "... oregonframework"
	@echo "... shared"
	@echo "... oregon-realm"
	@echo "... collision"
	@echo "... game"
	@echo "... game_pch_dephelp"
	@echo "... pch_Generate_game"
	@echo "... pch_Generate_scripts"
	@echo "... scripts"
	@echo "... scripts_pch_dephelp"
	@echo "... oregon-core"
	@echo "... map_extractor"
	@echo "... vmap_assembler"
	@echo "... vmap_extractor"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

